version: 3.1
services:
  app:
    image: node:8.7.0-alpine
    port: "8080:8080"
    volumes:
      - app-vol: ./app

  app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=psPass
    volumes: ./volumes/app-db

volumes:
  app-vol:
  app-db-vol:
