version: "3.2"
services:
  app-db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=postgres
      - PSTGRES_USER=postgres
      - POSTGRES_DB=prenetics
  app:
    image: node:8
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./app
        target: /app
    # command: ["./wait-for-it.sh", "app-db", "--", "npm", "start","--","prefix","./app/"]
    command: ./wait-for-it.sh app-db
    command: npm start --prefix ./app/
    depends_on:
      - app-db
    links:
      - app-db


# volumes:
# #   app-vol:
# #  app-db-data:
