version: "3.2"
services:
  app:
    image: node:8.7.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./app
        target: /app
    command:  npm start --prefix ./app/
    #
#   app-db:
#     image: postgres
#     environment:
#       - POSTGRES_PASSWORD=psPass
#     volumes:
#       - app-db-vol:./volumes/app-db
#
# volumes:
#   app-vol:
#   app-db-vol:
